### ISSUE TITLE
training bug

### ISSUE THREAD

**Issue by TIANTEA** [maybeLx/MVSFormerPlusPlus#3]
when i was trying to train the model on 4 3090 gpus, it failed. 
The problem is:

     "assert self._scale is not None, "Attempted {} but _scale is None.  ".format(funcname) + fix
AssertionError: Attempted step but _scale is None.  This may indicate your script did not use scaler.scale(loss or outputs) earlier in the iteration."

how can i fix this, thanks

**Comment by xingchen2022** [comment]
> when i was trying to train the model on 4 3090 gpus, it failed. The problem is:
> 
> ```
>  "assert self._scale is not None, "Attempted {} but _scale is None.  ".format(funcname) + fix
> ```
> 
> AssertionError: Attempted step but _scale is None. This may indicate your script did not use scaler.scale(loss or outputs) earlier in the iteration."
> 
> how can i fix this, thanks

how did you fix this? thanks!

**Comment by TIANTEA** [comment]
I change the batch size = 1,  and it works.
It is caused by "bs = self.scale_batch_map[str(imgs.shape[3])]", and mvsformer++.json
"scale_batch_map": {
                        "512": 4,
                        "576": 4,
                        "640": 4,
                        "704": 4,
                        "768": 2,
                        "832": 2,
                        "896": 2,
                        "960": 2,
                        "1024": 2
                    }"
I change all the scale_batch_map value to 1,and it works.

**Comment by TIANTEA** [comment]
xingchen lv, can wo add a wechat? I am also a phd student who focus on mvs and 3d recon.

**Comment by xingchen2022** [comment]
> xingchen lv, can wo add a wechat? I am also a phd student who focus on mvs and 3d recon.

sure, my wechat id is xc2022-wechat
